version: "3.1"
services:
  mongo:
    image: mongo:3.6
    container_name: mongo
    restart: always
    # volumes:
    #   - ./data/db:/data/db
    # ports:
    #   - 27017:27017

  bot-app:
    build: .
    container_name: bot-app
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGO_URL=<mongo_url>
      - TELEGRAM_BOT_TOKEN=<token>
      - TELEGRAM_CHAT_ID=<chat_id>
